name: key
description: ScanSafeAfrica v3.2.1 AI Inspector
publish_to: 'none'
version: 3.2.1+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  crypto: ^3.0.3
flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
